services:
    benborla.authorizenet.gateway_factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [Czende\GoPayPlugin\GoPayGatewayFactory]
        arguments: [BenBorla\AuthorizeNetPlugin\AuthorizeNetGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: authorizenet }

    benborla.authorizenet.form.type.gateway_configuration:
        class: BenBorla\AuthorizeNetPlugin\Form\Type\AuthorizeNetGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: authorizenet, label: Authorize.net }
            - { name: form.type }
